### PR TITLE
Update openfeature.md

### PR DESCRIPTION
**Pull request by DavidPHirsch**
## This PR
- updated information
- added adoption story
- added future plans

### CODE REVIEW

**Comment by DavidPHirsch** [comment]
@aepfli @beeme1mr @toddbaert i'm not able to add any reviewers, any ideas?

**Comment by aepfli** [comment]
it seems like this repo is missing from https://github.com/open-feature/community/blob/main/config/open-feature/org/workgroup.yaml

**Comment by toddbaert** [comment]
@DavidPHirsch We can add this repo to the permissions config, I'm just not sure where because I haven't been directly involved in the incubation application process.

Which team should be in charge? Do we need a new one? If you're OK with adding it [here](https://github.com/open-feature/community/blob/main/config/open-feature/org/workgroup.yaml) as @aepfli suggested, I can open a PR for that.

**Comment by DavidPHirsch** [comment]
@toddbaert sounds good

**Review by beeme1mr — APPROVED** [review]

**Pull request merged**
